In [61]:
import numpy as np

In [62]:
sample_input = '''498,4 -> 498,6 -> 496,6
503,4 -> 502,4 -> 502,9 -> 494,9'''

In [63]:
def load_data(sample_input):
    rocks = [rocks.split(' -> ') for rocks in sample_input.split('\n')]
    
    xs, ys= [], []
    for i in range(len(rocks)):
        for j in range(len(rocks[i])):
            x = int(rocks[i][j].split(',')[0])
            y = int(rocks[i][j].split(',')[1])
            rocks[i][j] = (x, y)
            xs.append(x)
            ys.append(y)

    min_x, max_x, min_y, max_y = min(xs), max(xs), min(ys), max(ys)
    
    return rocks, min_x, max_x, min_y, max_y

In [64]:
def create_area(min_x, max_x, min_y, max_y):
    return np.zeros((max_y+1, max_x-min_x+1))

In [65]:
def find_steps(tuple_1, tuple_2):
    results = [(tuple_1[0], tuple_1[1]), tuple_2]
    diff_x = abs(tuple_1[0] - tuple_2[0])
    for i in range(diff_x):
        if tuple_1[0] < tuple_2[0]:
            results.append((tuple_1[0]+i, tuple_1[1]))
        else:
            results.append((tuple_1[0]-i, tuple_1[1]))
    
    diff_y = abs(tuple_1[1] - tuple_2[1])
    for i in range(diff_y):
        if tuple_1[1] < tuple_2[1]:
            results.append((tuple_2[0], tuple_2[1]-i))
        else:
            results.append((tuple_2[0], tuple_2[1]+i))
    
    return results

In [66]:
def create_rocks(cave, rocks):
    for paths in rocks:
        for i in range(len(paths)-1):
            steps = find_steps(paths[i], paths[i+1])
            for step in steps:  # note that indexes in numpy array are changed
                cave[(step[1], step[0]-min_x)] = 1
                
    return cave

In [67]:
def falling_sand(cave, min_x):
    current_pos = [0, 500-min_x]
    comes_to_rest = False
    while not comes_to_rest:
        if cave[(current_pos[0]+1, current_pos[1])] == 0:
            current_pos[0] = current_pos[0]+1
        elif cave[(current_pos[0]+1, current_pos[1]-1)] == 0:
            current_pos[0] = current_pos[0]+1
            current_pos[1] = current_pos[1]-1
        elif cave[(current_pos[0]+1, current_pos[1]+1)] == 0:
            current_pos[0] = current_pos[0]+1
            current_pos[1] = current_pos[1]+1
        else:
            comes_to_rest = True
            cave[tuple(current_pos)] = 2
    
    return cave

In [68]:
def adding_units_of_sand(cave, min_x):
    i = 0
    while True:
        try:
            falling_sand(cave, min_x)
            i += 1
        except IndexError:
            break
            
    return i

In [69]:
rocks, min_x, max_x, min_y, max_y = load_data(sample_input)
cave = create_area(min_x, max_x, min_y, max_y)
cave = create_rocks(cave, rocks)
answer = adding_units_of_sand(cave, min_x)

In [70]:
answer

24

In [71]:
puzzle_input = open('Day 14.txt').read()

In [72]:
rocks, min_x, max_x, min_y, max_y = load_data(puzzle_input)
cave = create_area(min_x, max_x, min_y, max_y)
cave = create_rocks(cave, rocks)
answer = adding_units_of_sand(cave, min_x)

In [73]:
answer

779

# Part 2

In [115]:
def change_size(cave):
    cave = np.hstack([np.zeros((cave.shape[0], 1)), cave, np.zeros((cave.shape[0], 1))])
    cave[-1][-1] = 1
    cave[-1][0] = 1
    
    return cave

In [116]:
def create_area(min_x, max_x, min_y, max_y):
    cave = np.zeros((max_y+1+2, max_x-min_x+1))
    cave[-1] = 1
    
    return cave

In [117]:
def falling_sand(cave, min_x):
    current_pos = [0, 500-min_x]
    comes_to_rest = False
    while not comes_to_rest:
        if cave[(current_pos[0]+1, current_pos[1])] == 0:
            current_pos[0] = current_pos[0]+1
        elif cave[(current_pos[0]+1, current_pos[1]-1)] == 0:
            current_pos[0] = current_pos[0]+1
            current_pos[1] = current_pos[1]-1
        elif cave[(current_pos[0]+1, current_pos[1]+1)] == 0:
            current_pos[0] = current_pos[0]+1
            current_pos[1] = current_pos[1]+1
        else:
            comes_to_rest = True
            cave[tuple(current_pos)] = 2
    
    return cave

In [118]:
def adding_units_of_sand(cave, min_x):
    i = 0
    while cave[0, 500-min_x] != 2:
        try:
            cave = falling_sand(cave, min_x)
            i += 1
        except IndexError:
            cave = change_size(cave)
            min_x -= 1
            cave = falling_sand(cave, min_x)
            i += 1
            
        print(cave)
            
    return i

In [114]:
rocks, min_x, max_x, min_y, max_y = load_data(sample_input)
cave = create_area(min_x, max_x, min_y, max_y)
cave = create_rocks(cave, rocks)
answer = adding_units_of_sand(cave, min_x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 2. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 2. 2. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 

IndexError: index 12 is out of bounds for axis 1 with size 12

In [112]:
cave[0, 500-min_x]

0.0

In [110]:
cave

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 1., 1., 1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [111]:
change_size(cave)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [141]:
rocks, min_x, max_x, min_y, max_y = load_data(sample_input)
cave = create_area(min_x, max_x, min_y, max_y)
cave = create_rocks(cave, rocks)
answer = adding_units_of_sand(cave, min_x)


KeyboardInterrupt: 

In [129]:
def create_area(min_x, max_x, min_y, max_y):
    return np.zeros((max_y+1+2, (max_x-min_x+1)*100))

In [135]:
def falling_sand(cave, min_x):
    current_pos = [0, 500]
    comes_to_rest = False
    while not comes_to_rest:
        if cave[(current_pos[0]+1, current_pos[1])] == 0:
            current_pos[0] = current_pos[0]+1
        elif cave[(current_pos[0]+1, current_pos[1]-1)] == 0:
            current_pos[0] = current_pos[0]+1
            current_pos[1] = current_pos[1]-1
        elif cave[(current_pos[0]+1, current_pos[1]+1)] == 0:
            current_pos[0] = current_pos[0]+1
            current_pos[1] = current_pos[1]+1
        else:
            comes_to_rest = True
            cave[tuple(current_pos)] = 2
    
    return cave

In [140]:
def adding_units_of_sand(cave, min_x):
    i = 0
    while True:
        try:
            falling_sand(cave, min_x)
            i += 1
        except IndexError:
            break
            #cave = np.hstack([np.vstack([np.zeros(max_y), 1]), cave, np.vstack([np.zeros(max_y), 1])])
            #falling_sand(cave, min_x)
            #min_x += 1
            #i += 1
 
    return i

In [ ]:
answer

In [108]:
rocks, min_x, max_x, min_y, max_y = load_data(puzzle_input)
cave = create_area(min_x, max_x, min_y, max_y)
cave = create_rocks(cave, rocks)
answer = adding_units_of_sand(cave, min_x)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 168 and the array at index 1 has size 1

In [51]:
answer

779